### ISSUE TITLE
403 error when downloading image

### ISSUE THREAD

**Issue by pixelnull** [nixonjoshua98/manganelo#1]
```
C:\Users\pixelnull>python manga.py
Traceback (most recent call last):
  File "manga.py", line 16, in <module>
    dl = DownloadChapter(chapter.url, file)
  File "C:\Users\pixelnull\AppData\Local\Programs\Python\Python38-32\lib\site-packages\manganelo\api\downloadchapter.py", line 22, in __init__
    self._download_chapter()
  File "C:\Users\pixelnull\AppData\Local\Programs\Python\Python38-32\lib\site-packages\manganelo\api\downloadchapter.py", line 36, in _download_chapter
    image_paths = self._download_images(image_urls, temp_dir)
  File "C:\Users\pixelnull\AppData\Local\Programs\Python\Python38-32\lib\site-packages\manganelo\api\downloadchapter.py", line 77, in _download_images
    image = utils.send_request(url)
  File "C:\Users\pixelnull\AppData\Local\Programs\Python\Python38-32\lib\site-packages\manganelo\utils\__init__.py", line 38, in send_request
    r.raise_for_status()
  File "C:\Users\pixelnull\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://s6.mkklcdnv6.com/mangakakalot/d1/dead_dead_demons_dededededestruction/vol1_chapter_0_ddd_v1_chapter_extras/1.jpg
```

That's from a direct copy of the example code in the readme (with Naruto changed ofc). It got to "vol1_chapter_0_ddd_v1_chapter_extras" so I'm guessing it's correct all the way up until it gets a 403. Which I don't know what you would do about. I can access it when I go to the image directly in firefox 76.0.1, so it might just need a useragent change. I would pull it but don't really have time rn.

```
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0'}

r = requests.get(url, headers=headers)
```
That would probably work, but I'm not sure how it'd fit into your code.

Love the idea of the project and starred/followed it though.

**Comment by nixonjoshua98** [comment]
Thanks for this. I'll try and get a fix out today. `DownloadChapter` will most likely undergo a change soon, and It's good to see someone who uses the project!

**Comment by nixonjoshua98** [comment]
So the issue is that the URL you have provided is protected by `CloudFare` so it will reject requests. When I try to go to the URL I get a 1020 error which is `Access Denied`.

Although, I have changed the headers used to the headers provided by you.

 I will add better exception handling. I will leave this issue open for now as i may look into it again. That being said, if you find a reliable fix then feel free to drop it here and do a pull request.

**Comment by nixonjoshua98** [comment]
@pixelnull. Just to confirm, for this example are you using the URL `https://mangakakalots.com/chapter/dead_dead_demons_dededededestruction/chapter_0`?

**Comment by pixelnull** [comment]
Yes that's the chapter I'm trying to download, but really it would be all of the chapters for that manga.

It's tragic it's behind cloudflare though.

**Comment by nixonjoshua98** [comment]
@pixelnull. I think I have amended it.
