### ISSUE TITLE
Files are not properly saved when using different file name

### ISSUE THREAD

**Issue by MichalLauer** [nixonjoshua98/manganelo#10]
I used a different naming convention. When working with the default `f"./AoT {chapter.num}.pdf"`, download works. However, when I change it to `f"./AoT {chapter.title}.pdf"`, I get a blank file called "AoT Vol.1 Chapter 1" without any extension.

My guess is that since the chapter.title is 
'**_Vol.1 Chapter 1_**: To You, 2,000 Years From Now' 
and the blank file name is 
'**_AoT Vol.1 Chapter 1_**',
 the _downloadchapter.py_ script somehow doesn't work well with _:_ in the filename. 

My script for reference (used only to save the first chapter)

```
from manganelo import SearchManga,  MangaInfo, DownloadChapter
import os

search = SearchManga("Attack on Titan", threaded=False)
results = search.results
best_result = results[0]
manga_info = MangaInfo(best_result.url, threaded=False)
manga_page = manga_info.results

file = f"./AoT {manga_page.chapters[0].title}.pdf"
dl = DownloadChapter(manga_page.chapters[0].url, file)
results = dl.results
if results.saved_ok:
    print(results.path, results.percent_saved)
```

**Comment by nixonjoshua98** [comment]
Hi, nice catch. This was because Windows does not allow a small subset of characters to be in file names. I have added a quick string replace to remove them if they exist. I will update the PyPi version to 1.16.1 shortly.
