### ISSUE TITLE
Unable to search

### ISSUE THREAD

**Issue by drumildeshpande** [nixonjoshua98/manganelo#5]
Hi I tried using the library. However I get an empty list for anything I search

`search = SearchManga("Mythical Realm", threaded=True)`
`results = list(search.results())`

results is an empty list for me irrespective of the search query.

**Comment by nixonjoshua98** [comment]
I have noticed this. This is because the website has some issues currently and will have a sqlite error for no reason.

I will add it so it retries soon but for now, if you get an empty list then try again.

**Comment by nixonjoshua98** [comment]
This was an issue! I just had another look at it, Manganelo.com changed their search URL from /search/ to /search/story/. Version 1.5.1 fixes this issue so update your install.
