### ISSUE TITLE
Download Chapters Broken

### ISSUE THREAD

**Issue by dspec13** [nixonjoshua98/manganelo#6]
DownloadChapter(chapter.url, file) will always return a 2 page pdf.
[Naruto 0.pdf](https://github.com/nixonjoshua98/manganelo/files/5213443/Naruto.0.pdf)

**Comment by nixonjoshua98** [comment]
i have just looked into this and it seems that a lot of the site media has been moved behind Cloudfare, so it blocks downloading the images. I don't think there is anyway around this.

**Comment by Jaeger87** [comment]
https://stackoverflow.com/questions/36948573/download-files-from-website-with-cloudflare-using-python

Found this on stackoverflow, i'm going to try it and i let you know

**Comment by Jaeger87** [comment]
Ok, i tried but it seems that did not work :(

**Comment by jesk3r** [comment]
My new pull request should fix that problem. The get request has to have the correct header information for cloud flare to allow it.

**Comment by nixonjoshua98** [comment]
I haven't looked at the code yet but Manganelo all of a sudden has Cloudfare warnings over all their Manga..

**Comment by jesk3r** [comment]
Not sure what that is about. However I tried the code it worked as intended. Didn't change the code very much, just added a new header and method in the API class.
